### ISSUE TITLE
Reorder issue with Exaile 4

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#197] opened 2015-12-14 06:23 UTC
In Exaile 4 on Windows 8, I can't reorder songs in my playlist anymore by dragging and dropping, here's a GIF of the behavior:
http://i.imgur.com/XJHEhEf.gifv
I can see where the song should be ending up, but it just doesn't go there

**Comment by genodeftest** [comment] 2015-12-14 12:14
This issue is present on Linux (Fedora, Gtk+ 3.18.x) too.

**Comment by virtuald** [comment] 2015-12-14 15:14
I knew there was a drag and drop bug somewhere that I had forgotten about.

**Comment by tfree87** [comment] 2016-04-25 13:16
I found a few changes allow for some reordering, however, after about 4 'drag and drop' operations playlist reordering no longer works. I found that the playlist was ignoring drag and drop operations because of an error in string comparison and because of some name changes in methods associated with Gtk. This commit shows the changes that allow for this _partial restore_ of drag and drop function: https://github.com/tfree87/exaile/commit/58d20db0ba00628e541473b064c7a55ad4ce7c71 . I have yet to figure out why this only works for a limited number of operations.

**Comment by tfree87** [comment] 2016-04-29 14:48
I seem to have found why the 'drag-and-drop' operation doesn't always work. It appears that get_selected_rows() in xlgui/widgets/playlist.py sometimes returns and empty list for `paths` when `selection.get_selected_rows()` is called. This only happens when I do multiple 'drag-and-drop' operations on a single track. When I select multiple tracks, reordering is restored.

`def get_selected_paths(self):
        """
            Returns a list of pairs of treepaths which are currently
            selected in the playlist.
            
            The treepaths are returned for the base model, so they are
            indices that can be used with the playlist currently
            associated with this view.
        """
        selection = self.get_selection()
        model, paths = selection.get_selected_rows()
        
        if isinstance(model, Gtk.TreeModelFilter):
            paths = [model.convert_path_to_child_path(path) for path in paths]
        
        return paths`

Not quite sure how to address this issue.

**Comment by javiercantero** [comment] 2017-01-03 16:11
The commit d3819627973a893ced2886727c5910fe01a108e4 supersedes @tfree87's patch. I've tested it and it works, now you can reorder songs drag-and-dropping them.

However, there's another problem: after dropping the song, you need to click twice to select the next song to drag. If you don't do the second click, a d&d operation doesn't work.

Another problem (that probably should be considered a separate issue) is if the dragged song is the song being played: when dropped it loses any graphical sign of being played including the play icon.

 so this issue could be closed

**Comment by sbrubes** [comment] 2018-03-07 15:50
#484 could fix it.

@dangmai please, check if you have applied the right path because what [you post](https://github.com/exaile/exaile/pull/483#issuecomment-370270440), I could only reproduce on this patch, not #483.

**Comment by dangmai** [comment] 2018-03-08 02:16
@sbrubes I was running Exaile off of the `steal-dnd` branch by @virtuald branch. Was that the wrong patch?

**Comment by dangmai** [comment] 2018-03-08 14:22
I've tried that patch before and run into the same issue @javiercantero did - I needed to click twice to select another item.

**Comment by virtuald** [comment] 2018-03-09 02:29
Fixed in #484

**Closed by virtuald** 2018-03-09 02:29 UTC
Labels: GTK3/GST1.x, Type: regression
