### ISSUE TITLE
Seek slider and time not visible in version 4.0.0 beta

### ISSUE THREAD

**Issue by cipricus** [exaile/exaile#496] opened 2018-03-23 15:17 UTC
### Steps to Reproduce (for bugs)

Start the player

### Expected Behavior
A seek slider should be visible 
A time number should be visible close to the seek slider, or on it, something like here:

![deepinscrot-3917](https://user-images.githubusercontent.com/3447868/37838670-d65c8ca6-2eb8-11e8-8f66-9e5936fe4b0a.png)

### Current Behavior

1. Starting the player normally all seems well in place but the seek slider is not visible
2. Clicking with the mouse in the area where it should be it reacts as if present - I get to a different time point in the track
3. Numbers indicating time in the song are also absent on the interface     

![screenshot from 2018-03-23 16 27 02](https://user-images.githubusercontent.com/3447868/37838044-2ad5bfde-2eb7-11e8-8807-3fa0bca52482.png)

![deepinscrot-2647](https://user-images.githubusercontent.com/3447868/37838054-313f22fc-2eb7-11e8-82e3-4ba8c10386d1.png)

Starting Exaile in terminal I see this:

~$ exaile
INFO    : Loading Exaile 4.0.0beta3...
INFO    : Using Python 2.7.12
INFO    : Using PyGObject 3.20.0
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.31
INFO    : Using GStreamer 1.8.3
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.18.9
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
KeyError: 'could not find foreign type Context'

### Environment

* Operating System and version:

* Exaile Version: 4.0.0beta3
GStreamer: 1.8.3
GTK+: 3.18.9
Locale: en_US UTF-8
Mutagen: 1.31
PyGObject: 3.20.0
Python: 2.7.12

The operating system is Ubuntu Budgie 16.04 with Budgie desktop.

**Comment by virtuald** [comment] 2018-03-23 15:39
This seems to be a duplicate of https://github.com/exaile/exaile/issues/412 ... do you have python-gi-cairo installed? We should probably add that to the dependencies.

**Comment by cipricus** [comment] 2018-03-23 15:43
python-gi-cairo was not installed but was easy to install from synaptic 

Issue solved.

Do be closed as duplicate. Should I simply close it?

**Comment by virtuald** [comment] 2018-03-23 16:09
I updated the DEPS file with a note. Thanks!

**Closed** 2018-03-23 16:09 UTC
Labels: Status: duplicate
