### ISSUE TITLE
`__repr__` of a track shouldn't throw

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#328] opened 2017-04-21 06:09 UTC
This is the root cause of #229, and could potentially cause issues in the future if we're not careful. I don't have a strong opinion at the moment of the best solution.

An easy way to reproduce this is to open exaile with `--eventdebug-full` specified, open up the properties dialog on the file, and paste some invalid strings for the title field. When you save you'll see a few tracebacks from the logger when it the track `__repr__` failed.

**Comment by genodeftest** [comment] 2017-05-16 08:21
Isn't this fixed in 07b92495bbb50c7e48314bf55734249d313eb09f already? I cannot reproduce i t any more.

**Comment by sjohannes** [comment] 2017-05-16 08:30
Yeah, `repr(track)` now always returns an str with Unicode characters backslash-escaped (`\u1234`). The new format looks like `<Track u'Title' by u'Artist' from u'Album'>`.

**Closed by sjohannes** 2017-05-16 08:30 UTC
Labels: Status: help wanted, Type: bug
