### ISSUE TITLE
Playlist column widths forgotten on restart

### ISSUE THREAD

**Issue by 4ndyD** [exaile/exaile#580] opened 2019-01-07 21:01 UTC
### Steps to Reproduce (for bugs)
Quit and re-open Exaile.
This was observed after an upgrade to LM18.3 (based on U16.04) that broke some GStreamer codec plugin dependency for mp3 in the repository-provided version 3.3.2, causing [this bug](https://github.com/exaile/exaile/issues/35) despite all qualities of codec plugins being installed, resulting in me testing the latest version.

### Expected Behavior
The playlist columns should be at the same width as they were when the application last ran.

### Current Behavior
When Exaile starts after quitting, all columns are at their minimum width (nothing in the column can be read), except for the right-most column, which takes up the rest of the screen width.

Also, sometimes when dragging out the collapsed columns to appropriate widths, as soon as the edge of the last (left-most) column "\#" for track number is clicked on, the entire application crashes. This last part has been unreliable - e.g. it happened on the first 2 of 3 times this morning, but I only observed it so far on 4.0.0beta2, currently available as .deb installer via PPA.

There is also slightly different starting visual behaviour - in 4.0.0beta2, all the columns begin collapsed onto the same pixel-width, whereas in 4.0.0rc3, they begin with a few pixels regularly spaced between each column edge.

### Environment
Linux Mint 18.3 XFCE 32bit edition
Exaile 4.0.0rc3 from source
GStreamer: 1.8.3
GTK+: 3.18.9
GTK+ theme: Mint-X
Locale: en_GB UTF-8
Mutagen: 1.41.1
PyGObject: 3.20.0
Python: 2.7.12

Peculiarity - I also have Python 3.5 installed, but it seems to be defaulting to 2.7 when running.

I looked at another system already running LM18.3 64bit, and Exaile was not shown in the repository at all. Executing from the github release would not start, probably lacking dependencies.

**Comment by sjohannes** [comment] 2019-01-15 15:36
Hm, I can't reproduce the issue on my system. What I did to test this:

1. Resize the Artist colum to be very wide.
2. Restart Exaile.

And the column is still the same width. I also don't encounter the other weirdness that you get.

Could you run Exaile from a terminal and see if there are any error messages displayed?

**Comment by 4ndyD** [comment] 2019-01-15 18:14
Console output, two errors displayed:
```
INFO    : Loading Exaile 4.0.0beta2...
INFO    : Using Python 2.7.12
INFO    : Using PyGObject 3.20.0
INFO    : Loading settings...
INFO    : Using Locale en_GB UTF-8
INFO    : Using Mutagen 1.41.1
INFO    : Using GStreamer 1.8.3
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.18.9
INFO    : Loading plugins...
/usr/share/exaile/plugins/notifyosd/__init__.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
/usr/lib/exaile/xlgui/__init__.py:59: Warning: unable to set property 'rating' of type 'gint' from value of type 'gchararray'
  Gtk.main()

```

**Comment by sjohannes** [comment] 2019-01-16 05:37
I can reproduce this on Mint 18.3. Column width settings (`col_width_title` etc.) are saved properly, but the next time Exaile starts they become 3 except for the last column.

Automatic column sizing is not affected by this, so as a temporary workaround you may want to use that (View → Columns → Autosize).

**Comment by rokm** [comment] 2019-01-26 14:21
While #585 fixes the symptoms, it seems to me that the underlying cause of this problem is the delay on the ```on_width_changed``` callback (imposed by the ```glib_wait``` decorator). 

If the decorator is removed, the pattern of ```on_width_changed``` invocations changes, and when it is invoked for the first time, the column has correct width (as opposed to 0 which happens on first invocation of delayed version).

Interestingly, the non-delayed handler is called fewer times per column than the delayed one, so there may be a deeper interaction at play here, but so far I haven't been able to figure it out.

**Comment by sjohannes** [comment] 2019-01-27 09:34
The Mint 18.3 machine that I used for testing this just died, so unfortunately it's going to be difficult for me to help now (it doesn't happen on my Arch machine). Let me know if you figure it out or if you don't want #585 merged yet.

**Comment by rokm** [comment] 2019-01-27 12:30
You can merge #585 to have the bug fixed (the additional validation does not hurt anyway).

I will try to instrument the Gtk in my Mint 18.3 VM with some additional traces to see what is going on with the width, but my current hypothesis is that after column notifies us of the width change (with correct width), the width is internally modified/reset without notification (either because the column is being realized or because of resizing/realization of adjacent columns), and with the added delay, we pick up the modified value instead of the one we were supposed to be notified of...

**Comment by sjohannes** [comment] 2019-01-27 23:50
The delay is meant to prevent excessive processing. `common.glib_wait(100)` means that if the function gets called again within 100 ms, the first call is dropped. If the function gets called again within 100 ms of the second call, the second call is dropped.

I think the idea here is that `settings.set_option` may be somewhat expensive, so when the user is resizing a column by dragging the column separator we don't want to call it too often.

Perhaps a better fix is to call `get_width` without delay, but delay the `set_option` call. Something like this:

```py
def on_width_changed(self, column, widget):
    self._delayed_width_changed(self.get_width())

@common.glib_wait(100)
def _delayed_width_changed(self, width):
    if not self.destroyed and width != settings.get_option(
        self.settings_width_name, -1
    ):
        settings.set_option(self.settings_width_name, width)
```

**Comment by rokm** [comment] 2019-01-28 10:15
Indeed, that should both fix the problem and preserve the delayed behaviour.

**Closed** 2019-02-06 23:19 UTC
Labels: Type: regression
