### ISSUE TITLE
plugin 'Main Menu Button' causes segfault

### ISSUE THREAD

**Issue by madrats** [exaile/exaile#257] opened 2016-04-16 02:25 UTC
enabling the Main Menu Button works, but clicking on it causes exaile to segfault without any visible errors in the output

**Comment by genodeftest** [comment] 2016-04-16 07:02
Which version of Gtk+ are you running? I can reproduce this with gtk+ 3.20.0.

I can confirm the segfault. It is happening in `gtk_css_gadget_get_preferred_size`. Since the crash is happening deep inside Gtk+ code, I'll report it there.

**Comment by genodeftest** [comment] 2016-04-16 07:18
Reported upstream: https://bugzilla.gnome.org/show_bug.cgi?id=765134

**Comment by madrats** [comment] 2016-04-16 08:27
yeah, 3.20.3

**Comment by genodeftest** [comment] 2016-04-21 07:31
Upstream bug is fixed and will be released with Gtk+ 3.20.4.

**Comment by sjohannes** [comment] 2016-04-21 08:15
Thanks for testing and chasing this up with upstream. I've added a note to the plugins page and the draft release notes.

**Closed by sjohannes** 2016-04-21 08:15 UTC

**Comment by genodeftest** [comment] 2017-04-26 14:13
Upstream bug has not been backported to 3.20, but it has landed in 3.22, I'm updating the draft release notes.
