### ISSUE TITLE
Add Import/Export Playlist options to the popup context menu to improve discoverability

### ISSUE THREAD

**Issue by tlnagy** [exaile/exaile#23] opened 2015-01-05 17:35 UTC
As mentioned in #21, the addition of import/export playlist options to the popup menu that appears after right-clicking within the playlist tab would help discoverability of these options. There are already several playlist management ("Save", "Rename", etc) already listed there.

**Comment by virtuald** [comment] 2015-03-15 05:11
This is a duplicate of #47 .

**Closed by virtuald** 2015-03-15 05:11 UTC
