### ISSUE TITLE
Collection view glitchy with breeze-gtk and other themes

### ISSUE THREAD

**Issue by Fanael** [exaile/exaile#362] opened 2017-05-06 03:45 UTC
#The collection view is glitchy to the point of being unusable when using the [breeze-gtk](https://cgit.kde.org/breeze-gtk.git/) GTK theme.

Moving the mouse over the list results in artist names being drawn over separators and other artists. Seems to be related to the separators somehow, because it doesn't occur to the elements before the first separator.

Works fine with Adwaita instead.

Tested on Debian sid, using the current git master.

**Comment by sjohannes** [comment] 2017-05-06 04:26
Hm yeah. It works on most of the themes I have, but there are some with the same problem (e.g. Greybird).

**Comment by hotice** [comment] 2017-05-23 10:21
This also occurs with the default Ubuntu theme (Ambiance) in Ubuntu 17.04 (GTK 3.22), using the Exaile 4.0.0 beta 1 release.

**Comment by genodeftest** [comment] 2017-05-25 18:30
Do you get any warnings? How about when you run exaile with the `G_ENABLE_DIAGNOSTIC` environment variable set? e.g. `$ G_ENABLE_DIAGNOSTIC=foo exaile`?

This looks like a theme bug to me, but to be fair, Gtk+ developers made the lives of theme developers really hard lately.

**Comment by virtuald** [comment] 2017-05-28 21:57
This is a GTK/theme bug. I've created a simple script that you can use to show a treeview that glitches.

The bug goes away if you remove the call to `Gtk.TreeView.set_row_separator_func`... so I suppose we could try to detect the theme and just not call that function. However, I think I'd rather just call this a 'wontfix' and file a bug upstream.

* Reproducer script: https://gist.github.com/virtuald/1ae5538f3c5757c49c0bf9448fbe77b0
* Upstream bug report for breeze-gtk: https://bugs.kde.org/show_bug.cgi?id=380291

@hotice if you could test the reproducer script on your Ubuntu system... I suspect you'll get similar results. I don't have an Ubuntu system, so you could file a bug with them?

**Comment by hotice** [comment] 2017-06-15 09:54
Damn, I missed your mention, sorry. Indeed, the script reproduces this issue in Ubuntu 17.04 with the default theme (Ambiance). By the way, this also occurs with Linux Mint's Mint-y theme. 

Maybe a workaround is not a bad idea until this is fixed upstream... since these are popular themes.

**Comment by virtuald** [comment] 2017-06-15 16:47
Maybe if there are confirmations on the upstream bug, they'll pay attention to it?

**Comment by genodeftest** [comment] 2017-06-16 12:26
Is there an upstream bug against Ambiance (Ubuntu theme)?

**Comment by genodeftest** [comment] 2017-06-30 10:21
Upstream bug report on Ambiance/Radiance: https://bugs.launchpad.net/ubuntu-themes/+bug/1701512

@hotice : Do you reproduce the issue with Linux Mint's Mint-y theme on a recent version? If yes, can you please report a new issue on their bug tracer? You may just copy the KDE or Ambiance bug report.

**Comment by clobrano** [comment] 2017-07-08 10:31
Hi,

I'm trying to look into this. Any change to run gtk-inspector with exaile? I tried in the usual way, but it didn't work

**Comment by sjohannes** [comment] 2017-07-08 12:17
If Ctrl+Shift+I doesn't work, try running Exaile with the GTK_DEBUG environment variable set to `interactive`, e.g. by running `GTK_DEBUG=interactive exaile`.

It may be simpler to test the bug using Dustin's reproducer script from [a previous comment](https://github.com/exaile/exaile/issues/362#issuecomment-304543012). The bug happens on themes that don't properly support GtkTreeView's row separator feature.

**Comment by clobrano** [comment] 2017-07-08 12:32
Great, I didn't know Ctrl-Shift-I for gtk insepector.
I couldn't make it work setting env variable

**Comment by clobrano** [comment] 2017-07-08 15:32
I proposed a patch upstream for Ubuntu's Radiance theme. Let's see what happens.
If you like, please, have a try with the patched theme.

**Comment by genodeftest** [comment] 2017-09-19 13:39
@clobrano : Thanks!

According to [the upstream bug report at launchpad](https://bugs.launchpad.net/ubuntu-themes/+bug/1701512), the bug is fixed upstream with a bugfix released yesterday. Please note here if you can still reproduce that bug with the update installed.

**Closed by genodeftest** 2017-09-19 13:39 UTC
Labels: GTK3/GST1.x, Type: regression

**Comment by sjohannes** [comment] 2017-09-19 13:55
Thanks for fixing this on the Ubuntu themes. To anyone wanting to fix other affected themes, [this is the relevant commit](http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/revision/560).

**Comment by ShadeFrozen** [comment] 2018-12-07 13:04
Same issue still exists in the Breeze GTK themes on Xubuntu 18.04, due to a small spelling mistake in gtk.css.  In the dark variant, line 3538 reads:

treeview.view.seperator {
min-height: 2px;
color: #616569; }

and of course that should be **separator**. 

I know this thread is for exaile, but I didn't know where else to post and figured it might be helpful.

**Comment by genodeftest** [comment] 2018-12-07 17:56
@ShadeFrozen Can you please report that to Launchpad? You may want to link it to https://bugs.launchpad.net/ubuntu-themes/+bug/1701512.

**Comment by sjohannes** [comment] 2018-12-07 22:51
[Upstream fix](https://cgit.kde.org/breeze-gtk.git/commit/?id=a742b49636d958ab310a71fec4454e7fb00da584)
