### ISSUE TITLE
"è" character issue-4.0.0beta2

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#413] opened 2017-07-10 20:09 UTC
It looks I've got issue with "è" character.

I can't read this file: `08 - Après la pluie....flac` from collection.
error: Resource not found
The "è" was missing in the track name, also in the file path. Correct the track name don't solve the problem. On the capture the name was already corrected.
![exaile-e](https://user-images.githubusercontent.com/4454843/28037548-f9e57564-65bb-11e7-95f1-58138cc4ec75.png)

I can read the track from file brother. Here the "è" appears.

I think I also had issue with playlist name and "é" or "è".
![exaile-e-pl](https://user-images.githubusercontent.com/4454843/28038523-77db7b32-65bf-11e7-8985-7bcff0707318.png)
The list of playlists on the left and the content of "playlists" folder on the right does not match.

**Comment by sjohannes** [comment] 2017-07-14 00:45
### Track issue

Could you run Exaile from a terminal and post what it prints out when you try to play the track?

---

### Playlist issue

I think I've just fixed this in git, but your playlists may already be broken. To fix them:

1. Edit the `PLAYLIST_NAME.playlist` file, make sure there is a line like `name=U: PLAYLIST_NAME` near the bottom. If it doesn't exist, add the line (replacing `PLAYLIST_NAME` accordingly).
2. Edit `order_file` and add the playlist name there (before `EOF`).

Or if it's not important, you can just delete the .playlist files.

Note that this needs the git master version. If you run Exaile 4.0-beta2 they will break again....

**Comment by XzuRukneg** [comment] 2017-07-14 10:00
**Track issue**
```
~$ exaile /media/ZIC/Toute\ la\ Musique/ZIK/Musique\ \(Flac\)/Alain\ Caron\ le\ band\ -\ \"play\"/08\ -\ Après\ la\ pluie....flac 
INFO    : Loading Exaile 4.0.0beta2...
INFO    : Using Python 2.7.12
INFO    : Using PyGObject 3.20.0
INFO    : Loading settings...
INFO    : Using Locale fr_FR UTF-8
INFO    : Using Mutagen 1.31
INFO    : Using GStreamer 1.8.3
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.18.9
INFO    : Loading plugins...
INFO    : Loading collection...
/usr/local/lib/exaile/xl/playlist.py:2053: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  self.playlists = [n for n in ordered_playlists if n in existing]
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Playing file:///media/ZIC/Toute%20la%20Musique/ZIK/Musique%20(Flac)/Alain%20Caron%20le%20band%20-%20%22play%22/08%20-%20Apr%C3%A8s%20la%20pluie....flac
ERROR   : Playback error: serveur Jack introuvable
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
WARNING : Could not open file: Aucun fichier ou dossier de ce type
```
(just ignore the jack thing, I've not started my audio server for this test)

**Playlist isue**
Ok, thanks!
I'll not use git for some reason. So I'll wait the next release to test, ok for you?

**Comment by sjohannes** [comment] 2017-07-14 12:36
> ```
> /usr/local/lib/exaile/xl/playlist.py:2053: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   self.playlists = [n for n in ordered_playlists if n in existing]
> ```

This is related to the playlist issue, so hopefully it's fixed.

> ```
> INFO    : Playing file:///media/ZIC/Toute%20la%20Musique/ZIK/Musique%20(Flac)/Alain%20Caron%20le%20band%20-%20%22play%22/08%20-%20Apr%C3%A8s%20la%20pluie....flac
> ```

This looks fine to me. Does the track play?

Something else you can try is run Exaile with `--debug` and see if there are other relevant messages.

> ```
> WARNING : Could not open file: Aucun fichier ou dossier de ce type
> ```

I think this is from the multialarmclock plugin, probably not related.

> I'll not use git for some reason. So I'll wait the next release to test, ok for you?

Sure, that's alright.

**Comment by XzuRukneg** [comment] 2017-07-14 13:08
> This looks fine to me. Does the track play?
Like that, yes. Sorry my test is just not relevant, and I also see I've miss the GUI error on my screenshots.
So, now if I try to play it from the collection:

```
~$ exaile 
INFO    : Loading Exaile 4.0.0beta2...
INFO    : Using Python 2.7.12
INFO    : Using PyGObject 3.20.0
INFO    : Loading settings...
INFO    : Using Locale fr_FR UTF-8
INFO    : Using Mutagen 1.31
INFO    : Using GStreamer 1.8.3
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.18.9
INFO    : Loading plugins...
INFO    : Loading collection...
/usr/local/lib/exaile/xl/playlist.py:2053: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  self.playlists = [n for n in ordered_playlists if n in existing]
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
WARNING : Could not open file: Aucun fichier ou dossier de ce type
INFO    : Playing file:///media/ZIC/Toute%20la%20Musique/ZIK/Musique%20(Flac)/Alain%20Caron%20le%20band%20-%20%22play%22/08%20-%20Apr%20s%20la%20pluie....flac
ERROR   : Playback error: Ressource introuvable
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
```
![exaile-e-pl2](https://user-images.githubusercontent.com/4454843/28213402-3c4e06f4-68a6-11e7-8a28-5bf8697c5d1f.png)

Here, it don't play.

**Comment by sjohannes** [comment] 2017-07-14 13:42
Ah, now this is interesting.

> INFO    : Playing file:///media/ZIC/Toute%20la%20Musique/ZIK/Musique%20(Flac)/Alain%20Caron%20le%20band%20-%20%22play%22/08%20-%20Apr%20s%20la%20pluie....flac

The `%20` in `Apr%20s` is a space character. I don't know how, but it seems that somehow there's a broken path in the database.

Could you try doing *Tools &rarr; Rescan Collection (slow)* and see if that fixes it?

If that still doesn't work, try re-creating the database (close Exaile, delete/move `~/.local/share/exaile/music.db`, run Exaile, and add the collection again).

**Comment by genodeftest** [comment] 2017-07-14 14:41
if @sjohannes is right, this might be the same as #188

**Comment by XzuRukneg** [comment] 2017-07-14 17:16
> if @sjohannes is right, this might be the same as #188 

Yes, I also use an old database. I've tried also to read other file with "é" or "è" in the track name from collection: can't read.

I'll test the Rescan.

**Comment by genodeftest** [comment] 2017-07-27 16:08
@XzuRukneg : Did rescanning the database work around the encoding issue for you?

**Comment by XzuRukneg** [comment] 2017-07-30 10:35
Yes, it does.

**Comment by genodeftest** [comment] 2017-07-30 10:57
Closing as duplicate of #188 then. Thanks for confirming!

**Closed by genodeftest** 2017-07-30 10:57 UTC
